--CREATE TABLE participacao_evento (
--    id TEXT PRIMARY KEY UNIQUE NOT NULL,
--    usuario_id TEXT NOT NULL,
--    evento_id TEXT NOT NULL,
--    FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
--    FOREIGN KEY (evento_id) REFERENCES eventos(id)
--);
